FROM ghcr.io/mehdi-ra/vmaf:latest

# Install build dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    autoconf automake build-essential ca-certificates cmake \
    git libtool meson ninja-build pkg-config texinfo wget unzip yasm

# Install libdav1d for AV1 software decoding
RUN git clone https://code.videolan.org/videolan/dav1d.git && \
    cd dav1d && \
    meson setup build && ninja -C build && ninja -C build install && ldconfig

# (Optional) Install libaom for AV1 support too
RUN apt-get install -y --no-install-recommends libaom-dev

# Download and build FFmpeg
ARG FFMPEG_TAG=master
ARG NVCC_FLAGS="-gencode arch=compute_75,code=sm_75 -gencode arch=compute_75,code=compute_75 -O2"

RUN wget https://github.com/FFmpeg/FFmpeg/archive/${FFMPEG_TAG}.zip && \
    unzip ${FFMPEG_TAG}.zip

RUN cd FFmpeg-${FFMPEG_TAG} && ./configure \
    --pkg-config-flags="--static" \
    --enable-gpl \
    --enable-nonfree \
    --enable-libdav1d \
    --enable-libaom \
    --enable-libvmaf \
    --enable-nvdec \
    --enable-nvenc \
    --enable-cuvid \
    --enable-cuda \
    --enable-cuda-nvcc \
    --enable-libnpp \
    --enable-ffnvcodec \
    --disable-stripping \
    --nvccflags="${NVCC_FLAGS}" && \
    make -j$(nproc) && \
    make install && \
    ldconfig

# Create a convenient data directory
RUN mkdir /data

ENTRYPOINT ["ffmpeg"]
